# DouYinCommand.py 配置文件
# 必需配置项

# 下载链接列表
link:
  # - https://v.douyin.com/gNv_ZvhuEr0/
  - https://v.douyin.com/3uGJzMxBwTI/

# 下载保存路径
path: ./Downloaded/

# 下载线程数
thread: 5

# 下载模式 (主页链接时生效)
mode:
  - post

# 下载数量限制
number:
  post: 3      # 作品数量 (0表示全部)
  like: 3      # 喜欢数量
  music: 3     # 音乐数量
  mix: 3       # 合集数量
  allmix: 3    # 所有合集数量

# 增量下载设置
increase:
  post: false
  like: false
  music: false
  mix: false
  allmix: false

# 下载内容设置
music: true       # 下载背景音乐
cover: true       # 下载封面
avatar: true      # 下载头像
json: true        # 保存JSON信息
database: true    # 使用数据库
folderstyle: true # 按文件夹分类

# 时间过滤
start_time: ''
end_time: ''

# Cookie配置 (可选)
cookie: ''

# 或使用键值对方式
cookies:
  msToken: my7nuKyrpTVEWOX-n62wR8I5EcvoMKBmvsBMnODLOtG3sn6AsR7q_jEM5jmEenyuwmHpsL25b84VhGcR4nUgv0PepA2zrSUOGHCmZVzpauYpRgbR9svMKjt2-AgNRz
  sessionid: bd1856d28d3592573fc43c7bec5194d6
  sessionid_ss: bd1856d28d3592573fc43c7bec5194d6
  sid_guard: bd1856d28d3592573fc43c7bec5194d6%7C1757747080%7C5184000%7CWed%2C+12-Nov-2025+07%3A04%3A40+GMT
  sid_tt: bd1856d28d3592573fc43c7bec5194d6
  ttwid: 1%7CmmH7jXEeDQziYDU1ZbV5bzf7luuM31p6Knl_Q6cpRJI%7C1757747088%7C8bae7013a3e95043c556c8d512917ba723c9ff0f629ddc6f9f23bb0d1bc7972c
  uid_tt: 0db1165d183a178f06d70ff7b1543a51
  uid_tt_ss: 0db1165d183a178f06d70ff7b1543a51