link:
  - https://www.douyin.com/user/MS4wLjABAAAA6O7EZyfDRYXxJrUTpf91K3tmB4rBROkAw-nYMfld8ss

path: ./Downloaded/

music: true
cover: true
avatar: true
json: true

start_time: ""
end_time: ""

folderstyle: true

mode:
  - post

number:
  post: 1
  like: 0
  allmix: 0
  mix: 0
  music: 0

increase:
  post: false
  like: false
  allmix: false
  mix: false
  music: false

thread: 5
retry_times: 3
database: true

cookies:
  msToken: YOUR_MS_TOKEN
  ttwid: YOUR_TTWID
  odin_tt: YOUR_ODIN_TT
  passport_csrf_token: YOUR_CSRF_TOKEN
  sid_guard: YOUR_SID_GUARD
